name: pkg-config_installer-0.29.2 CI

on:
  pull_request:
    paths:
      - 'recipes/pkg-config_installer/0.29.2**'
      - 'build.py'
      - '.github/workflows/pkg-config_installer-0.29.2.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/pkg-config_installer/0.29.2**'
      - 'build.py'
      - '.github/workflows/pkg-config_installer-0.29.2.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}

jobs:
  pkg-config_installer:
    strategy:
      matrix:
        build: ['linux-gcc4.8', 'linux-gcc8', 'linux-gcc9']
        pkg-config_installer_versions: ['0.29.2']
        include:
          - build: 'linux-gcc4.8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '4.8'
            docker_image: 'conanio/gcc48'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'conanio/gcc8'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
          - build: 'linux-gcc9'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '9'
            docker_image: 'conanio/gcc9'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/pkg-config_installer/0.29.2
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          CONAN_REFERENCE: pkg-config_installer/${{ matrix.pkg-config_installer_versions }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
